
from fpdf import FPDF
import os

def generate_summary_text(address, valuation, cash_offer, comps):
    summary = f"""
PROPERTY SUMMARY REPORT

📍 Address: {address}
💰 Estimated Value (AVM): ${valuation:,}
💸 60% ARV Cash Offer: ${cash_offer:,}
📑 Creative Subto Offer: Full price + seller equity payout terms

Recent Comparable Sale:
{comps[0] if comps else 'N/A'}

This analysis was automatically generated by Jerry, your creative finance deal analyzer.
"""
    return summary

def create_pdf_report(address, valuation, cash_offer, comps, output_path):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    summary = generate_summary_text(address, valuation, cash_offer, comps)
    for line in summary.strip().split("\n"):
        pdf.cell(200, 10, txt=line.strip(), ln=True)

    pdf.output(output_path)
    return output_path
